### ISSUE TITLE
打开127.0.0.1：5000，显示Notfound

### ISSUE THREAD

**Issue by NRD90M** [li-keli/Robot_NLP#7]
Not Found
The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

**Comment by li-keli** [comment]
In fact, there is a routing address in /semantic

**Comment by NRD90M** [comment]
访问http://127.0.0.1:5000/semantic
Traceback (most recent call last):
  File "E:\QA\Robot_NLP-master\controllers\api.py", line 27, in semantic
    if not json_data['msg']:
TypeError: 'NoneType' object is not subscriptable
2020/07/27 12:01:09 PM INFO [ _internal.py._log.88 ] - 127.0.0.1 - - [27/Jul/2020 12:01:09] "GET /semantic?1 HTTP/1.1" 200 -
这个程序具体该怎么用呢，可以提供下data和使用教程嘛，刚入门

**Comment by li-keli** [comment]
this git repository has been abandoned and is not recommended for learning
